### ISSUE TITLE
Import the data into db

### ISSUE THREAD

**Issue by kris914g** [luk1337/csgolounge-api#2]
Hi is it possible with this script to import all the matches into a db? with the data? and how because i don't understand the Java part in the example

**Comment by luk1337** [comment]
You can modify api.php to save array $output to db or something else. BTW it's PHP, not Java.

**Comment by kris914g** [comment]
okay but where in the code is it? can you pls tell me. This Api is really cool ;D

**Comment by luk1337** [comment]
There is no db support already in code, you need to write it yourself.

**Comment by kris914g** [comment]
okay thanks
