### ISSUE TITLE
Is it possiple to save thoes matches into a database 

### ISSUE THREAD

**Issue by kris914g** [luk1337/csgolounge-api#3]
Hi is it possible to save all the matches into a DB? i have already made a db stricture like this: because i don't know how to do it ;(

table name: matches
id            : int:unsigned
team1_id      : int:unsigned
team2_id      : int:unsigned
team1_pct     : int
team2_pct     : int
csgolounge_id : int
time          : timestamp
winner_id     : int:nullable
live          : bool
link          : string
updated_at    : timestamp

table name: teams
id   : int
name : string
logo : string

**Comment by luk1337** [comment]
you need to write your own code to do that.
